"""Model deployment recipes — the console as the place where a model gets
deployed, not just used.

A recipe is a parameterised, reviewable plan: it renders the exact shell
script, service unit and litellm entry for one way of serving a model, so
the operator reads what will run before it runs. Deploying executes the
script over ssh on the target host and streams its output; registering
appends the litellm entry and restarts the gateway. Everything here is
plain text and stdlib — no templating engine, nothing hidden.
"""

from __future__ import annotations

import json
import shlex


def _p(name, label, default="", help="", kind="text", choices=None):
    d = {"name": name, "label": label, "default": default, "help": help, "kind": kind}
    if choices:
        d["choices"] = choices
    return d


# ------------------------------------------------------------------ vLLM --
VLLM_CUDA = {
    "id": "vllm-cuda",
    "title": "vLLM on a CUDA GPU (Linux or WSL2)",
    "summary": "A small, fast model for agents on any NVIDIA card: uv venv + vLLM, tool calling on, "
               "a systemd user service that survives reboots, and a litellm entry so the console and "
               "the harness see it by name.",
    "target": "ssh",
    "params": [
        _p("host", "ssh host", "", "an ssh alias the console can reach without a password (e.g. agents-worker)"),
        _p("model", "Hugging Face model", "Qwen/Qwen3-4B-AWQ", "AWQ/GPTQ 4-bit fits 8 GB; Qwen3 and Llama 3.x support tool calling"),
        _p("served_name", "served model name", "qwen3-4b-fast", "the name litellm, the console and the harness will use"),
        _p("port", "port", "8001", "", "number"),
        _p("max_model_len", "context window (tokens)", "24576", "KV cache is what is left after the weights: 8 GB ≈ 25k tokens for a 4B AWQ model", "number"),
        _p("max_num_seqs", "concurrent sequences", "3", "how many agents can be served at once", "number"),
        _p("gpu_mem", "GPU memory fraction", "0.85", "leave room for the desktop on a shared card", "number"),
        _p("dtype", "dtype", "half", "half for Turing/Volta (no bf16); auto for Ampere+", "select", ["half", "auto", "bfloat16"]),
        _p("tool_parser", "tool-call parser", "hermes", "hermes for Qwen; llama3_json for Llama 3.x; mistral for Mistral", "select", ["hermes", "llama3_json", "mistral", "pythonic"]),
        _p("reasoning_parser", "reasoning parser", "qwen3", "strips hidden reasoning from replies; blank to disable", "select", ["qwen3", "deepseek_r1", ""]),
        _p("venv", "venv path", "~/vllm-env", ""),
        _p("lan_ip", "LAN address of the host", "", "for the litellm entry; on WSL2 this is the Windows box's LAN IP (needs a portproxy, see notes)"),
    ],
}


def _render_vllm_cuda(p):
    port = int(p["port"]); venv = p["venv"]
    args = [
        "serve", p["model"], "--host", "0.0.0.0", "--port", str(port),
        "--served-model-name", p["served_name"], "--max-model-len", str(int(p["max_model_len"])),
        "--max-num-seqs", str(int(p["max_num_seqs"])), "--gpu-memory-utilization", str(float(p["gpu_mem"])),
        "--dtype", p["dtype"], "--enable-auto-tool-choice", "--tool-call-parser", p["tool_parser"],
    ]
    if p.get("reasoning_parser"):
        args += ["--reasoning-parser", p["reasoning_parser"]]
    serve_sh = "#!/bin/bash\n# generated by the ByteBunker console\nexport PATH=/usr/lib/wsl/lib:$PATH\nexec %s/bin/vllm %s\n" % (
        venv, " ".join(shlex.quote(a) for a in args))
    install_sh = f"""#!/bin/bash
# vLLM on a CUDA GPU — generated by the ByteBunker console
set -e
export PATH="$HOME/.local/bin:/usr/lib/wsl/lib:$PATH"
if curl -s -m 3 http://127.0.0.1:{port}/v1/models 2>/dev/null | grep -q {shlex.quote(p['served_name'])}; then
  echo "== {p['served_name']} is already serving on port {port}; nothing to do (stop its service first to redeploy)"; exit 0
fi
echo "== gpu"; nvidia-smi --query-gpu=name,memory.total,driver_version,compute_cap --format=csv,noheader
command -v gcc >/dev/null || {{ echo "!! no C compiler: run  sudo apt install -y build-essential  (vLLM's Triton kernels need it)"; exit 2; }}
command -v uv >/dev/null || curl -LsSf https://astral.sh/uv/install.sh | sh
[ -x {venv}/bin/python ] || uv venv {venv} --python 3.12
uv pip install --python {venv}/bin/python vllm huggingface_hub
{venv}/bin/python -c "import vllm, torch; print('vllm', vllm.__version__, 'torch', torch.__version__, 'cuda', torch.cuda.is_available())"
{venv}/bin/python -c 'from huggingface_hub import snapshot_download; print(snapshot_download({json.dumps(p['model'])}))'
cat > ~/vllm-{p['served_name']}.sh <<'SERVE'
{serve_sh}SERVE
chmod +x ~/vllm-{p['served_name']}.sh
mkdir -p ~/.config/systemd/user
cat > ~/.config/systemd/user/vllm-{p['served_name']}.service <<'UNIT'
[Unit]
Description=vLLM {p['served_name']} ({p['model']})
After=network.target

[Service]
ExecStart=%h/vllm-{p['served_name']}.sh
Restart=on-failure
RestartSec=15
StandardOutput=append:%h/vllm-{p['served_name']}.log
StandardError=append:%h/vllm-{p['served_name']}.log

[Install]
WantedBy=default.target
UNIT
systemctl --user daemon-reload
systemctl --user enable --now vllm-{p['served_name']}.service
echo "== waiting for the engine"
for i in $(seq 1 36); do
  sleep 10
  if curl -s -m 3 http://127.0.0.1:{port}/v1/models | grep -q {shlex.quote(p['served_name'])}; then echo "== up: http://127.0.0.1:{port}/v1"; exit 0; fi
  grep -q "Engine core initialization failed" ~/vllm-{p['served_name']}.log 2>/dev/null && {{ echo "!! engine failed to start:"; grep -E "ERROR|Error" ~/vllm-{p['served_name']}.log | tail -5; exit 3; }}
done
echo "!! not up after 6 min; see ~/vllm-{p['served_name']}.log"; exit 4
"""
    lan = p.get("lan_ip") or "<host-lan-ip>"
    litellm = ("  - model_name: %s\n    litellm_params:\n      model: openai/%s\n      api_base: http://%s:%d/v1\n      api_key: \"not-needed\"\n"
               % (p["served_name"], p["served_name"], lan, port))
    notes = [
        "Rootless, no sudo: everything lives under the ssh user's home and a systemd USER unit (needs `loginctl enable-linger <user>` once).",
        "On WSL2 the service listens inside the VM. Expose it on the Windows LAN address in an admin PowerShell:\n"
        "  netsh interface portproxy add v4tov4 listenaddress=0.0.0.0 listenport=%d connectaddress=<wsl-ip> connectport=%d\n"
        "  netsh advfirewall firewall add rule name=\"vllm-%d\" dir=in action=allow protocol=TCP localport=%d" % (port, port, port, port),
        "Turing cards (RTX 20xx, compute 7.5) run vLLM's Triton attention backend, no FlashAttention; use dtype half.",
        "Then: Register in litellm (below) and set the harness `default_slave_model` to the served name.",
    ]
    return {"files": [("install-and-serve.sh", install_sh), ("serve.sh", serve_sh)],
            "litellm_entry": litellm, "notes": notes, "api_base": "http://%s:%d/v1" % (lan, port),
            "model_name": p["served_name"], "deploy_script": install_sh}


# ---------------------------------------------------------------- Ollama --
OLLAMA_WIN = {
    "id": "ollama-windows",
    "title": "Ollama on Windows (native)",
    "summary": "The quickest small model on a Windows box with an NVIDIA card: Ollama already speaks the "
               "OpenAI API with tool calling. This recipe prints the PowerShell steps and the litellm entry; "
               "Windows has no ssh target for the console, so you run them.",
    "target": "manual",
    "params": [
        _p("model", "Ollama model tag", "qwen3:4b", "qwen3:4b / qwen3:8b / llama3.1:8b — tool-capable tags"),
        _p("lan_ip", "LAN address of the Windows host", "", ""),
        _p("port", "port", "11434", "", "number"),
        _p("parallel", "parallel requests", "3", "OLLAMA_NUM_PARALLEL — each costs KV memory", "number"),
    ],
}


def _render_ollama_win(p):
    port = int(p["port"]); lan = p.get("lan_ip") or "<host-lan-ip>"
    ps = f"""# Ollama on Windows — run in an ADMIN PowerShell (generated by the ByteBunker console)
winget install -e --id Ollama.Ollama            # skip if installed
[Environment]::SetEnvironmentVariable("OLLAMA_HOST", "0.0.0.0:{port}", "Machine")
[Environment]::SetEnvironmentVariable("OLLAMA_NUM_PARALLEL", "{int(p['parallel'])}", "Machine")
[Environment]::SetEnvironmentVariable("OLLAMA_KEEP_ALIVE", "24h", "Machine")
netsh advfirewall firewall add rule name="ollama-{port}" dir=in action=allow protocol=TCP localport={port}
Stop-Process -Name ollama,"ollama app" -ErrorAction SilentlyContinue; Start-Process "ollama" -ArgumentList "serve"
ollama pull {p['model']}
Invoke-RestMethod http://127.0.0.1:{port}/v1/models
"""
    served = p["model"].replace(":", "-").replace("/", "-")
    litellm = ("  - model_name: %s\n    litellm_params:\n      model: openai/%s\n      api_base: http://%s:%d/v1\n      api_key: \"not-needed\"\n"
               % (served, p["model"], lan, port))
    notes = ["Ollama serves one request at a time per model unless OLLAMA_NUM_PARALLEL is set; it does not batch like vLLM.",
             "Tool calling works for the tags listed above; hidden reasoning is off for Qwen3 when you pass think=false (the console does)."]
    return {"files": [("ollama-setup.ps1", ps)], "litellm_entry": litellm, "notes": notes,
            "api_base": "http://%s:%d/v1" % (lan, port), "model_name": served, "deploy_script": None}


# ------------------------------------------------------------- DGX Spark --
VLLM_SPARK = {
    "id": "vllm-dgx-spark",
    "title": "vLLM on DGX Spark (docker, one or two nodes)",
    "summary": "The big engine: vLLM in NVIDIA's container on a Spark, optionally tensor-parallel across two "
               "Sparks over the direct link. Renders the docker run for review; deploy runs it over ssh.",
    "target": "ssh",
    "params": [
        _p("host", "ssh host", "spark-1", ""),
        _p("model", "model path or HF id", "", "a local path under /models or a Hugging Face id"),
        _p("served_name", "served model name", "", ""),
        _p("port", "port", "8888", "", "number"),
        _p("max_model_len", "context window (tokens)", "131072", "", "number"),
        _p("image", "container image", "nvcr.io/nvidia/vllm:latest", ""),
        _p("tp", "tensor parallel (GPUs)", "1", "2 = both Sparks, needs VLLM_HOST_IP + TP_SOCKET_IFNAME on the head", "number"),
        _p("head_ip", "head node IP on the direct link", "192.168.100.1", "only for tp=2"),
        _p("ifname", "direct-link interface", "enp1s0f0np0", "only for tp=2"),
        _p("extra", "extra vllm args", "--enable-prefix-caching", ""),
    ],
}


def _render_vllm_spark(p):
    port = int(p["port"]); tp = int(p["tp"])
    env = ""
    if tp > 1:
        env = "  -e VLLM_HOST_IP=%s -e TP_SOCKET_IFNAME=%s \\\n" % (p["head_ip"], p["ifname"])
    run = f"""#!/bin/bash
# vLLM on DGX Spark — generated by the ByteBunker console
set -e
docker rm -f serve_node 2>/dev/null || true
docker run -d --name serve_node --gpus all --ipc=host --network host --restart unless-stopped \\
  -v /models:/models -v ~/.cache/huggingface:/root/.cache/huggingface \\
{env}  {p['image']} \\
  vllm serve {shlex.quote(p['model'])} --host 0.0.0.0 --port {port} --served-model-name {shlex.quote(p['served_name'] or 'model')} \\
  --max-model-len {int(p['max_model_len'])} --tensor-parallel-size {tp} {p.get('extra') or ''}
echo "== waiting"; for i in $(seq 1 90); do sleep 10; curl -s -m 3 http://127.0.0.1:{port}/v1/models | grep -q model && {{ echo up; exit 0; }}; done
docker logs --tail 30 serve_node; exit 4
"""
    litellm = ("  - model_name: %s\n    litellm_params:\n      model: openai/%s\n      api_base: http://172.19.0.1:%d/v1\n      api_key: \"not-needed\"\n"
               % (p["served_name"] or "model", p["served_name"] or "model", port))
    notes = ["172.19.0.1 is the docker-bridge address litellm uses to reach the host's vLLM on the Spark; adjust if litellm runs elsewhere.",
             "Two-node tensor parallel needs the same command on the second Spark as a worker (ray) — follow NVIDIA's DGX Spark playbook for the worker side."]
    return {"files": [("run-spark.sh", run)], "litellm_entry": litellm, "notes": notes,
            "api_base": "http://<spark-lan-ip>:%d/v1" % port, "model_name": p["served_name"] or "model", "deploy_script": run}


# The DGX Sparks are NOT a console recipe: they are driven by `rack`
# (bytebunkerlabs/dgx-spark-serve), whose recipes/*.env already express solo
# vs tensor-parallel launches and gateway registration. The console wraps
# rack (see server.py /api/rack) instead of re-inventing it.
RECIPES = {r["id"]: r for r in (VLLM_CUDA, OLLAMA_WIN)}
_RENDER = {"vllm-cuda": _render_vllm_cuda, "ollama-windows": _render_ollama_win}


def catalog():
    return [{k: r[k] for k in ("id", "title", "summary", "target", "params")} for r in RECIPES.values()]


def render(recipe_id, params):
    r = RECIPES.get(recipe_id)
    if not r:
        raise KeyError("no such recipe")
    p = {x["name"]: str(params.get(x["name"], x["default"]) if params.get(x["name"], None) not in (None, "") else x["default"]) for x in r["params"]}
    for x in r["params"]:
        if x["kind"] == "number":
            float(p[x["name"]])          # ValueError surfaces as a 400
    out = _RENDER[recipe_id](p)
    out["params"] = p
    return out


def litellm_register_script(cfg_path, container, entry):
    """Idempotent append of a model entry to litellm's config + restart."""
    return (
        "set -e\nF=%s\ngrep -q %s \"$F\" && { echo 'already registered'; exit 0; }\n"
        "cp \"$F\" \"$F.bak-$(date +%%Y%%m%%d-%%H%%M%%S)\"\n"
        "python3 - <<'EOF'\nimport re\np=%s\ns=open(p).read()\nentry=%s\n"
        "m=re.search(r'(?m)^model_list:\\s*$', s)\n"
        "s = s[:m.end()] + '\\n' + entry + s[m.end():] if m else s + '\\nmodel_list:\\n' + entry\n"
        "open(p,'w').write(s)\nprint('entry added')\nEOF\n"
        "docker restart %s >/dev/null && sleep 8 && docker logs %s --since 30s 2>&1 | grep -iE 'error|Application startup complete' | tail -3\n"
        % (shlex.quote(cfg_path), shlex.quote("model_name: " + entry.split("model_name:")[1].split("\n")[0].strip()),
           json.dumps(cfg_path), json.dumps(entry), shlex.quote(container), shlex.quote(container)))
